#!/bin/bash

##################################################################################################
# This is used to quickly configure a raspberry pi with the docker images created by this repository.
# Simply run `./install` and this will install docker, required docker plugins, and the service used
# to automatically run all docker images.
##################################################################################################

# Validates directory
if [[ `basename $PWD` != "install" ]];
then
    echo "Failed to install. Please run this script from within the 'install/' directory."
    exit
fi

echo "Updating build tools..."

# Update apt
apt-get update

# Install build tools
apt-get install build-essential libssl-dev libffi6 libffi-dev python-dev

# Docker Installation
# Docs: https://docs.docker.com/engine/install/debian/

echo "Downloading Docker..."

# ContainerIO download
wget https://download.docker.com/linux/raspbian/dists/bullseye/pool/stable/armhf/containerd.io_1.6.9-1_armhf.deb

# Docker Engine CLI
wget https://download.docker.com/linux/raspbian/dists/bullseye/pool/stable/armhf/docker-ce-cli_23.0.1-1~raspbian.11~bullseye_armhf.deb

# Docker Engine
wget https://download.docker.com/linux/raspbian/dists/bullseye/pool/stable/armhf/docker-ce_23.0.1-1~raspbian.11~bullseye_armhf.deb

# Docker Extras
wget https://download.docker.com/linux/raspbian/dists/bullseye/pool/stable/armhf/docker-ce-rootless-extras_23.0.1-1~raspbian.11~bullseye_armhf.deb

# Docker Compose
wget https://download.docker.com/linux/raspbian/dists/bullseye/pool/stable/armhf/docker-compose-plugin_2.6.0~raspbian-bullseye_armhf.deb

# Docker BuildX Plugin
wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/armhf/docker-buildx-plugin_0.10.2-1~debian.11~bullseye_armhf.deb

echo "Installing Docker..."

# Install downloaded files
dpkg -i containerd.io_1.6.9-1_armhf.deb
dpkg -i docker-ce-cli_23.0.1-1~raspbian.11~bullseye_armhf.deb
dpkg -i docker-ce_23.0.1-1~raspbian.11~bullseye_armhf.deb
dpkg -i docker-ce-rootless-extras_23.0.1-1~raspbian.11~bullseye_armhf.deb
dpkg -i docker-compose-plugin_2.6.0~raspbian-bullseye_armhf.deb
dpkg -i docker-buildx-plugin_0.10.2-1~debian.11~bullseye_armhf.deb

# Makes buildx
docker buildx install

echo "Installing Docker user..."

# Add the "docker" user to the user group and add a group named "docker"
# This is required to run docker without sudo
usermod -aG docker $USER
newgrp docker

echo "Installing climate service..."

# Copy service file to /etc/systemd/system/ and comopse file to home directory
cp ./climate.service /etc/systemd/system/
cp ./docker-compose.yml /home/pi

# Reload systemcl
systemctl daemon-reload

# Enable service
systemctl enable climate

echo "Rebooting..."

# Reboot the system
# This is required so that Adafruit drivers install properly
reboot