# Generated by Django 3.2.9 on 2021-11-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='humidity',
            field=models.CharField(editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='temperature',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
