# Generated by Django 3.2.9 on 2021-11-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211103_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='humidity',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='temperature',
            field=models.CharField(max_length=6),
        ),
    ]
