# Generated by Django 3.2.9 on 2021-11-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211103_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
