# Generated by Django 3.2.9 on 2021-11-04 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_climatedata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='humidity',
            field=models.FloatField(max_length=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='temperature',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='climatedata',
            constraint=models.CheckConstraint(check=models.Q(('humidity__gte', 0.0), ('humidity__lte', 100.0)), name='humidity_range'),
        ),
    ]
