# Generated by Django 3.2.9 on 2021-11-04 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20211104_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='humidity',
            field=models.FloatField(editable=False, max_length=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='temperature',
            field=models.FloatField(editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
