# Generated by Django 3.2.9 on 2021-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20211108_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='device',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
