# Generated by Django 3.2.9 on 2021-11-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_devicedata_device'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='climatedata',
            index=models.Index(fields=['-time'], name='time_idx'),
        ),
    ]
