# Generated by Django 3.2.9 on 2021-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_climatedata_time_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
